import { MigrationInterface, QueryRunner } from "typeorm"

export class migrations1662562180089 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(
            `
            INSERT INTO tableName (id,email,name,password) VALUES ('140', 'gbertsch@biovet-alquermes.com', 'Germán', '$2y$10$I8csuspUkMriMb2SR1hk4OJwHKBXgpNo9zKGoUmlPPD0fEbAK1mkW');
            INSERT INTO tableName (id,email,name,password) VALUES ('141', 'rarboix@kromschroeder.es', 'RAMON', '$2y$10$03RaYc6RvAAXgUJgOYqM6eZ6ydngA6w9YwEThkpGxdtAyjoZv1Hwu');
            INSERT INTO tableName (id,email,name,password) VALUES ('142', 'costa.toni302@gmail.com', 'TONI', '$2y$10$cu6.5XC/GRdM4OEAHFAgBuJGurR3YBgffKSpjSXOXJVJu01CQLRbq');
            INSERT INTO tableName (id,email,name,password) VALUES ('161', 'm.quirozl@solintsahn.com', 'Marco Antonio', '$2y$10$ed9/GnstQmIK7gDeRZ3pg.NI1NBGGzFV8dlCwg4HSxUKou7JYzuKO');
            INSERT INTO tableName (id,email,name,password) VALUES ('183', 'fpinto@ckmperu.com', 'Fernanda', '$2y$10$as7yofYyXLr5oo2abm7Ci.sBpKOAMWScspIzyYc4EIJqfwZ57trhC');
            INSERT INTO tableName (id,email,name,password) VALUES ('187', 'rafa.erb@gmail.com', 'Rafael', '$2y$10$tAGp2FUKchsZHD0AnsjKJOdI7Hq3zGfCuotgvaBuf7wO/QaL8FP1K');
            INSERT INTO tableName (id,email,name,password) VALUES ('188', 'mateog12@yahoo.com', 'Mateo', '$2y$10$NdXjMwbuoPpLTOX6j8WClus4NRliEhUcziEgSONOr9jI/ANWS4.g.');
            INSERT INTO tableName (id,email,name,password) VALUES ('189', 'reclutamiento@bandasavicolas.com', 'Erik Daniel', '$2y$10$N27OXJKu18je7B8fSH2fquYwubSo5KIwzLfrb3McCXdpO6cQmOoUm');
            INSERT INTO tableName (id,email,name,password) VALUES ('205', 'jose.jollja@unmsm.edu.pe', 'Felipe', '$2a$12$TIHhx0cmeH1tlUW3Wu.wxOB/DQSnt2VtDcgVQckqM9WMKUku2d/Vi
            ');
            INSERT INTO tableName (id,email,name,password) VALUES ('206', 'm2tejeda@outlook.com', 'MIRNA MARGARITA', '$2y$10$IGquFQGKZ6gBHca0fCFR0OFzme0cIusSJrNsNwEw/Lx5axoeaFqG.');
            INSERT INTO tableName (id,email,name,password) VALUES ('208', 'adja@tecnoditivos.com', 'Adja Fatou', '$2y$10$GASaFleazeopM4sbukN17eQE2zzXjFmQZHrlxS8Slb.c8q2mSO6oW');
            INSERT INTO tableName (id,email,name,password) VALUES ('209', 'sergio@tecnoaaditivos.com', 'Sergio', '$2y$10$5v9s6rt6C3onQhMdz9D6geguIgyZXG7KwRbW0OG3fIl1jXfvgCdVC');
            INSERT INTO tableName (id,email,name,password) VALUES ('210', 'fgc.sa@outlook.es', 'JESUS GABRIEL', '$2y$10$A534KipBVRGkmyrIfEN7zOzLi95ObywvZRa0A2qe6MNCuOBPy6.Cu');
            INSERT INTO tableName (id,email,name,password) VALUES ('213', 'alexhorvath@mtech-systems.com', 'Alejandro', '$2y$10$4KWU/C8HdFBmw5bFwPLPQ.0n9Lhk4TVBlWx4UDJWUKUy0JvGlS0tS');
            INSERT INTO tableName (id,email,name,password) VALUES ('214', 'rafaelramirez@mtech-systems.com', 'Rafael', '$2y$10$ctvG8fQzGc1DHQxLizI8qeFd/S4flMgGXsix8lnDGGzfc58ARV3de');
            INSERT INTO tableName (id,email,name,password) VALUES ('215', 'ernesto.cordoba@marel.com', 'Ernesto', '$2y$10$VfAoVq0KWa7Ohos3jAem8OnGr9gULC0pyGmoTr68Bj2vVRDEmizky');
            INSERT INTO tableName (id,email,name,password) VALUES ('216', 'michel.ochoa@marel.com', 'Michel', '$2y$10$ItD4vXnPo5B6vCUwzuyi/uNBwVR282YJrots3iIZhOVKSqZNQONUa');
            INSERT INTO tableName (id,email,name,password) VALUES ('267', 'vetfernandoacuna@gmail.com', 'fernando', '$2y$10$.C1beSwD9ExAUS8U2WFGd.eTvxBEuAoRC9IWNg2OEjpV9CchQivH.');
            INSERT INTO tableName (id,email,name,password) VALUES ('268', 'vfromentin@raiz-up.com', 'Vitor', '$2y$10$Mae6RXgI0OhRNJEGZKOrzeZyaHHHCaY2.7OH9KLsFdL/FojyEgkDq');
            INSERT INTO tableName (id,email,name,password) VALUES ('277', 'Humberto.Pedraja@roxell.com', 'HUMBERTO', '$2y$10$PK7PS02/ZCNZ5oo9e0zZe.ARV9cqMy0UXHDIY78QAau0EidL2y4.q');
            INSERT INTO tableName (id,email,name,password) VALUES ('278', 'jbaide@agrocs-inc.com', 'JOSE', '$2y$10$31ltFyJLPb2uMF6X4Q6cf.mOmgsZhWgYZ4x5UE.5.r9ZaLhq1L6.O');
            INSERT INTO tableName (id,email,name,password) VALUES ('280', 'bogar.martinez@irco.com', 'Bogar', '$2y$10$OWf9Cii7CTJJYA9cebju0eWj5XrvkXpWqVdMxObjBKVAnchUmrFB.');
            INSERT INTO tableName (id,email,name,password) VALUES ('281', 'rafaeleduardo.tenorio@maximus-solution.com', 'Rafael', '$2y$10$L4fDm2Dtwo1c9Fp6W46vzuGk8LDVMLSaIC3.qGmqSK21LLsDFRZyG');
            INSERT INTO tableName (id,email,name,password) VALUES ('283', 'mlehenaff@maximus-solution.com', 'Mathieu', '$2y$10$FWYuFAIvhF.m9r7tFhZUQ.8F9Ug2vk1FNCc8b35usZzJqeGeLDwH6');
            INSERT INTO tableName (id,email,name,password) VALUES ('286', 'bkoborg@jacobscorp.com', 'Bruce', '$2y$10$yT5OmclcEsH1DyBAFjBVd.0NKfCI4/0AQLM0eXOgLTBCB98gywn9a');
            INSERT INTO tableName (id,email,name,password) VALUES ('296', 'emilie.jougla@kersia-group.com', 'Emilie', '$2y$10$bpD.QbhJ6zHYN0GM8cpdkOkjEgQfwaGVCVyJehU7.POAIcs2.12SG');
            INSERT INTO tableName (id,email,name,password) VALUES ('297', 'nathalie.nuguet@kersia-group.com', 'Nathalie', '$2y$10$38S9sSZ5W9XmbcHGTHTjiOcwYOCBnlK0ERX0xrPcoK63duOfsILKq');
            INSERT INTO tableName (id,email,name,password) VALUES ('314', 'albonilla_00@hotmail.com', 'Ana Lucía', '$2y$10$.LqyW7kZYhNPRiaMQ/ESPe4XXmY2FId835zxaBVoNbi..X.MMK5He');
            INSERT INTO tableName (id,email,name,password) VALUES ('317', 'rcanseco@jacobscorp.com', 'Ruben', '$2y$10$O.yJRcKTQ/T31HN7BOG3l.wJ08mtb6bdk/4UFMe7yOCU5SQiaCdPW');
            INSERT INTO tableName (id,email,name,password) VALUES ('320', 'ricardo@yucca.com.mx', 'Ricardo', '$2y$10$X0qcYTMHtfmPoCGobf66d.O7FfP0R7zCU9zBbkRYbmSIcYuy8OJzi');
            INSERT INTO tableName (id,email,name,password) VALUES ('327', 'mescobar@globe-ingredients.com', 'Marcela', '$2y$10$ZmmK66wZirXEVs5Ci9zFdOMn/N5Rxd6UNxSYt6hXzZe1mYtuIPFYO');
            INSERT INTO tableName (id,email,name,password) VALUES ('328', 'javiervalladares@outlook.com', 'Javier', '$2y$10$kKhnf6XeQX/adna8SctYyu6RPqKTQhv/Q/omF49eRv/xlgKYVOGfK');
            INSERT INTO tableName (id,email,name,password) VALUES ('335', 'j_ponce@covesa.com.gt', 'Julio Roberto', '$2y$10$3YaW591PnuTsg4AcIvV3leCqwYNRiqEKdSjSein.2KHs2YVXVtWwm');
            INSERT INTO tableName (id,email,name,password) VALUES ('336', 'marialara.8912@gmail.com', 'María Argentina', '$2y$10$/nG6QOtlMwRrmLEWLDXpluk1smM/yYr51u9dyoLZ47pgB10QAY5xG');
            INSERT INTO tableName (id,email,name,password) VALUES ('343', 'cass.marroquin@gmail.com', 'Cassandra', '$2y$10$8tMco5SP2fCajkCOs17kT.UGLYkKUuZPSRCGcBIXlJ2oiSkzhsAOy');
            INSERT INTO tableName (id,email,name,password) VALUES ('358', 'jose.gorosabel@moba.net', 'Jose', '$2y$10$LBSpz7ootUaYNWHW4nzgq.MiOkar5ilR17BkOCx42PFA.6rbcH0PO');
            INSERT INTO tableName (id,email,name,password) VALUES ('366', 'diana.milagros7@gmail.com', 'Diana', '$2y$10$SYIVhPnY/aIKn9PCFoQ8BOaeyrgVsagAMyTHSC7sZU9j457fR2Ug2');
            INSERT INTO tableName (id,email,name,password) VALUES ('369', 'andres@reovotec.com', 'Andres', '$2y$10$Gm5k2Ojymo.G6MeZ/nqOzegx5q1c74jjNRFJyrku8RiFj2YIql6Kq');
            INSERT INTO tableName (id,email,name,password) VALUES ('371', 'israri001@hotmail.com', 'Israel', '$2y$10$d.U9W/1w9pKV8ERxN/fHEu8mzNs8zsQwzLHBL.7Gy7JHFLE2gmEQG');
            INSERT INTO tableName (id,email,name,password) VALUES ('384', 'john.ge@famsungroup.com', 'NINGNING', '$2y$10$3Cy39gRYVzpjdqIJ7uUFPuGs.pC3A5t4OzOIEIyVMFv3ZZ0wTD9Qy');
            INSERT INTO tableName (id,email,name,password) VALUES ('391', 'trade3@baffeed.com', 'Mutlu', '$2y$10$87KUBXqZlWjTi3rvCftjn.8Cd.rAqJx.EMaEaT1RvUd6ixPoZBHbC');
            INSERT INTO tableName (id,email,name,password) VALUES ('392', 'muran@baffeed.com', 'Mehmet', '$2y$10$HSNdFfypjGSCsP5S4m7oMOPsaxQHu3n.1E80tXNXnLUbEm8yo7Y/m');
            INSERT INTO tableName (id,email,name,password) VALUES ('398', 'yangguan216@163.com', 'GUAN', '$2y$10$pic8sLM5op1V1wei9n6tOuKxTkEAXZ7F8eNQsBEXqCjccvODzsKWe');
            INSERT INTO tableName (id,email,name,password) VALUES ('399', 'fmendez@seinvsa.com', 'FRANCISCO ANTONIO', '$2y$10$.CElM7vKOm0Vb4TJe.aaf./ISQOc26Zfhn9dcnhWZlGPk.zpahBye');
            INSERT INTO tableName (id,email,name,password) VALUES ('412', 'gonzalezsantiago91@gmail.com', 'Santiago', '$2y$10$izlXOMTLJcurcSzd90cx0.HFVT3hIxRgZSAiHPBoVXR27V8YfQGyS');
            INSERT INTO tableName (id,email,name,password) VALUES ('430', 'aploperena@yucca.com.mx', 'Alfredo Pablo', '$2y$10$06HWEyqcyM28CPjr9WGOJ.ZN95Y7Kx1igcwaL8Fn2VIHhlbZAcSii');
            INSERT INTO tableName (id,email,name,password) VALUES ('436', 'claudio.henriquez@salmet.de', 'Claudio', '$2y$10$C8iRqLcyOlVw9QTqP/fyxu6JlGRSxchSwQeuBQJXRMviguaeT67Wu');
            INSERT INTO tableName (id,email,name,password) VALUES ('437', 'antonio.herrera@salmet.de', 'Antonio', '$2y$10$VcrYEd8xB44kCBbWBgHFvehHdiqr1sEyy.E6rNxRQP1ygOJudi7aC');
            INSERT INTO tableName (id,email,name,password) VALUES ('441', 'maguilar@lhisa.com', 'Marcos', '$2y$10$cOTNUN7MEEf4D4Xazcx5jeuDaGE54rTdxGfASkYrVbTCC7CtoQ4Sy');
            INSERT INTO tableName (id,email,name,password) VALUES ('443', 'jmartinez@lhisa.com', 'Jordi', '$2y$10$lLQgd81UsDozMr/7bX3w8eUzOZs3ooAsJsxJcLnJi6aCSSa04ZwxG');
            INSERT INTO tableName (id,email,name,password) VALUES ('447', 'gustavo.zucami@gmail.com', 'Gustavo', '$2y$10$VQFlKAIcUmB08bZ2VnVGFOccg4KWziCIJ.NUiRwOkGGZ8uRELqBHG');
            INSERT INTO tableName (id,email,name,password) VALUES ('448', 'soporte.avicultura@gmail.com', 'Enrique', '$2y$10$TF.FeeA.uI1TEULWwzqepex5oN6gJ2QbkQxkeoSEydIxBw9bubR0G');
            INSERT INTO tableName (id,email,name,password) VALUES ('449', 'jalberto@catalysis.es', 'Juan Alberto', '$2y$10$O2Fp2N4Llzk12nK68Fr/w.Q/X3CG3q5A2U164JiJsOa8EkxHRVWuG');
            INSERT INTO tableName (id,email,name,password) VALUES ('451', 'asavin@catalysis.es', 'German', '$2y$10$X636dH/uvTyZ11POyoyVPO9lEnqU6ituO9hgPsfRq487c2RXxFXiu');
            INSERT INTO tableName (id,email,name,password) VALUES ('454', 'midec_1@yahoo.com', 'Mike', '$2y$10$K5wDxB9wTSqYyX6ncwG4T.8KEPMRP6EU/CNxUJhTDF3QR9.8T3t9G');
            INSERT INTO tableName (id,email,name,password) VALUES ('455', 'david.gramman@cpmroskamp.com', 'David', '$2y$10$g1cc2injHnEG5D1If5ZVEued.7AyaGVq45gI9Bc9OfHeFuMTafDIq');
            INSERT INTO tableName (id,email,name,password) VALUES ('456', 'omelgar.midec@outlook.com', 'Osmin', '$2y$10$im0liryR7qC6H7afqsi4X.lBRk9Jnp0xFXta4CZEFSuTSb/ED48zi');
            INSERT INTO tableName (id,email,name,password) VALUES ('458', 'nmorris@uspoultry.org', 'Nath', '$2y$10$Zi8wghzTk2lENb7FrCgVZeFYtTzVMm1Cd8Eq4hjKIBsIEyNkFqLke');
            INSERT INTO tableName (id,email,name,password) VALUES ('459', 'paola.cifuentes@premex.co', 'PAOLA', '$2y$10$L9nIdrToE.NQ7Oe6kI.np.oxaZOpykKg7iBlmuCI2i0M7Qr6/dRSu');
            INSERT INTO tableName (id,email,name,password) VALUES ('468', 'jorge.castro@churchdwight.com', 'Jorge', '$2y$10$wFLgF12ve.z9eTgVS7FUwueQdEONcNoQWsDzggmrbjGdBxR0XcQR6');
            INSERT INTO tableName (id,email,name,password) VALUES ('497', 'Christian.rippe@churchdwight.com', 'Christian', '$2y$10$SgbmjazUlOuxAxajyK4Q9OpU74Sv7IWck3EDJiMBPdOQX8H/wfX3W');
            INSERT INTO tableName (id,email,name,password) VALUES ('513', 'francisco.reyes@sevein.com.mx', 'FRANCISCO', '$2y$10$AI1RK3xeitg/zSjZRsDrrOydYDFHskKaU.tMJ0YIN0W7DAor41jC2');
            INSERT INTO tableName (id,email,name,password) VALUES ('514', 'diego_de_leo_septien@yahoo.it', 'Diego', '$2y$10$YqAMrC2qyBKJmm9RdTouK.Dxk91dhUCy03wgL3jnzIzcXk.mZCqpi');
            INSERT INTO tableName (id,email,name,password) VALUES ('515', 'dks@sanovogroup.com', 'David', '$2y$10$Iu3bR3nW/wTzY46SopsJUe0dll1ZM3uJtK/02rFriOYkdEV/7RO/i');
            INSERT INTO tableName (id,email,name,password) VALUES ('516', 'mejia5961@gmail.com', 'Jesus', '$2y$10$UI71q1VmeIQUN03.AptvkOHCEsKE9.6LoH6t3F0ppttnMMA/Uz0MK');
            INSERT INTO tableName (id,email,name,password) VALUES ('520', 'jbello@indiv.com', 'Jorge', '$2y$10$0.4v1KNN0fn6nG.07IFlte.RU91CDa/zyTEqMMvEL1QItFlom6hS2');
            INSERT INTO tableName (id,email,name,password) VALUES ('536', 'contacto@soloindustrias.com', 'Denise Josue', '$2y$10$RSxAA7UacR4bRQUKzK71LusbpRdI2TAJVJ8GVbr2.TzKO8nhxjN/S');
            INSERT INTO tableName (id,email,name,password) VALUES ('537', 'admon@bandasavicolas.com', 'Jordana Mireyra', '$2y$10$DFIzLXt7tJvAK00.daHZt.ggNTr9ywf.zX/.noBhjFi.j7AEZ7UgO');
            INSERT INTO tableName (id,email,name,password) VALUES ('538', 'ibanez@formatoib.com.br  ', 'MARCO', '$2y$10$zNiuRRN4ZU4G1NqTE5odFej90N56eNxPL9CFv5eaK/wv3eqTwPksu');
            INSERT INTO tableName (id,email,name,password) VALUES ('539', 'nadia.mancia@imprexhn.com', 'NADIA', '$2y$10$Q71IwRe7GkMuE/Gpbuu4SOvSpoWl.uo8q8C3H5CfTICqoExdLkw7i');
            INSERT INTO tableName (id,email,name,password) VALUES ('540', 'apedroza@aviagen.com', 'ANGELA', '$2y$10$KVDMC/D9BS7OlQ1suEzQ3uJKl7by4CekY3/mX.qbWoLgxWQBFEqSy');
            INSERT INTO tableName (id,email,name,password) VALUES ('546', 'rodrigo.scabora@facco.net', 'RODRIGO', '$2y$10$wbqnXlmx2kwmCJimak6jGuj6KD.dybsLiUwCcC4WFqIv2cQNZar02');
            INSERT INTO tableName (id,email,name,password) VALUES ('550', 'manuel.penalva@gmail.com', 'Manuel Enrique', '$2y$10$PsDJFIeW5bMLrU9o3xeBs.bPuq2vZ9XZ6XbW9rLkm6JiUlkSQ530m');
            INSERT INTO tableName (id,email,name,password) VALUES ('551', 'mepc74@hotmail.com', 'Manuel Enrique', '$2y$10$AfIbSw2UAcbbN0SF5JSyc.GetgB4hZ9BzSYrAp10cnY7lrsfNQiyu');
            INSERT INTO tableName (id,email,name,password) VALUES ('552', 'ventas@tekpro.com.co', 'Wilmar E.', '$2y$10$BJTW.vj2vAm.mCOlH2sYXeM1WVaPm8sXttxCWuFJ3O.zjY1DKrJre');
            INSERT INTO tableName (id,email,name,password) VALUES ('553', 'gerencia@tekpro.com.co', 'Alejandro', '$2y$10$y031YdTGxC9D4mK6Tp4FbOJkxWjQaqz3p4wXF0ajOgFJjJAQhB/xO');
            INSERT INTO tableName (id,email,name,password) VALUES ('554', 'leandro@artabas.com.br', 'LEANDRO', '$2y$10$9NIz/7JQljV6ZmbVjmuPJ.LI7NKpASqSDBorPpI/8IE32LzK1WZiK');
            INSERT INTO tableName (id,email,name,password) VALUES ('555', 'fabrizio.geroto@artabas.com.br', 'FABRIZIO', '$2y$10$iyelwrnAVH1s3//ZQxDBvuY2yhHQ0YVL0qz0reftJWvxleKnucyUC');
            INSERT INTO tableName (id,email,name,password) VALUES ('556', 'mpatriciajo@hotmail.com', 'MARIA PATRICIA', '$2y$10$1FDWLEWxvTKlBgkzuGKyLuZy39TuUovjCrrolYcGuvIweIzOiPsle');
            INSERT INTO tableName (id,email,name,password) VALUES ('557', 'x_castropozo_2202@hotmail.com', 'XAVIER JESUS', '$2y$10$nNGS87EF3oIg7tVspj1MCeTT51VtQEzRB7X4RPoPPlynoCRYqfMGy');
            INSERT INTO tableName (id,email,name,password) VALUES ('580', 'wilsonap@sephnos.com', 'Wilson', '$2y$10$O0u1hv0TiCZK1EFJUwwXe.tg75zQH7u4givRmSyt2sD/3z5qN8Ahm');
            INSERT INTO tableName (id,email,name,password) VALUES ('594', 'luis.anguiano@jat.com.mx', 'LUIS', '$2y$10$eLw38KCllC7SrzOVwkGoKexw78FvvAmdoFL7O08YBKEPSWSmLGUwW');
            INSERT INTO tableName (id,email,name,password) VALUES ('595', 'Leonardo.Ribeiro@jrsla.com.br', 'Leonardo', '$2y$10$6ujaszubGh3yhYmqs1qVs.b8geVLlbpCqnx65BonRlCNlOD7C5WZW');
            INSERT INTO tableName (id,email,name,password) VALUES ('596', 'josselinn.ambrocio@trouwnutrition.com', 'Josselinn', '$2y$10$a1u8umFCNkTYdyi3aRnJzuFyGaN0ObhnwsQg7TiE8Pta.YumTnv/e');
            INSERT INTO tableName (id,email,name,password) VALUES ('638', 'christian.pava@dosatronusa.com', 'Christian', '$2y$10$X92fwOjZaAcZirMDsAgX7.bd/f65ML0HOIOSNCuC6NvowUIXBqfLS');
            INSERT INTO tableName (id,email,name,password) VALUES ('640', 'ymejia@disatyr.com.ni', 'YELBA', '$2y$10$nG8CMv6SjXuGZhBm16DQFeIbEccD5S.2hY1E4EMXCO0NkX9zw3OJW');
            INSERT INTO tableName (id,email,name,password) VALUES ('645', 'scarlettamezquita@sephnos.com', 'Scarlett', '$2y$10$353MIWReZKx4AxjGtPOWJ.Ej8lXpgtV4K4Eg0/gypa1IMUGVmGrWO');
            INSERT INTO tableName (id,email,name,password) VALUES ('646', 'daniel.garciasalas@premexcorp.com', 'DANIEL', '$2y$10$fb.pdtL7COqy8agRA6gUYugs9Iyawiiz6nl9Fa8mI5O6YwLuSzo3G');
            INSERT INTO tableName (id,email,name,password) VALUES ('647', 'paola.sempe@premexcorp.com', 'PAOLA', '$2y$10$efDNIikRnN641sM1Ph8MXeZLVSdRiR0rgWhODM0k7Feul/RDTtknG');
            INSERT INTO tableName (id,email,name,password) VALUES ('648', 'rodolfo.rossal@premexcorp.com', 'RODOLFO ALBERTO', '$2y$10$kK8evYYIxl7Ki200BUq76ekSlVtoN.7HlDAF59IEbMdw2RCDp1XKK');
            INSERT INTO tableName (id,email,name,password) VALUES ('655', 'tyller@dominant-cz.cz', 'Milan', '$2y$10$4zETXTt0uYwHrM.WbONQEe3IxSn0q02isia/5bekJzz9jlwPVjhba');
            INSERT INTO tableName (id,email,name,password) VALUES ('659', 'sjoerd.tromp@barentz.nl', 'Sjoerd', '$2y$10$SaIhnr7rIkBO3YdUWkg.QOKdVm/.roy6Zz5t5OFh/E8lQFXsKZCmS');
            INSERT INTO tableName (id,email,name,password) VALUES ('664', 'tapialacayo@gmail.com', 'MARIA GABRIELA', '$2y$10$9fn1O8MLrymbGcUQSFign.OQhZlwkx7H5SArcMBCe/JojU5uUweSe');
            INSERT INTO tableName (id,email,name,password) VALUES ('665', 'bismarktapia@gmail.com', 'JOSE BISMARK', '$2y$10$QHwqOFm3dit2.Gy9rpDZr.iX6XSHgxJLi/1E0UcBFD4e2zVT8wfF.');
            INSERT INTO tableName (id,email,name,password) VALUES ('692', 'gregorio.lopez@hendrix-genetics.com', 'Gregorio', '$2y$10$E1iluW5izTG/S3caT8x3tu193AhZK8IA992oM9p2fUEEwUwDd46pO');
            INSERT INTO tableName (id,email,name,password) VALUES ('694', 'Romain.rouzaud@hendrix-genetics.com', 'Romain', '$2y$10$aDQFqb1KG7fBSbVsbnzYgu81jzZ8aFsPmBnGm64fa9faONhTSop3O');
            INSERT INTO tableName (id,email,name,password) VALUES ('695', 'Edouard.perrault@hendrix-genetics.com', 'Edouard', '$2y$10$WM87nwtxdbG/80Xo.PhBHOk2Ht.xq2D5i6.i6hjpAkKhs1j//2HsK');
            INSERT INTO tableName (id,email,name,password) VALUES ('696', 'Hugo.camacho@hendrix-genetics.com', 'Hugo', '$2y$10$a9JnR8Vw9aczXR9oTvlabeOJRZ5QfjQTy5TtUFosXmbcnB2tLR1ra');
            INSERT INTO tableName (id,email,name,password) VALUES ('705', 'Ignacio.moneta@miavit.com', 'IGNACIO', '$2y$10$mQ81BjPrS5gZJGNTgp1iY.eXRfKgzzi2EygqyWozFffuFPuLJ5znO');
            INSERT INTO tableName (id,email,name,password) VALUES ('706', 'javier.prieto@miavit.es', 'JAVIER', '$2y$10$LSRK/zoRz.LG9WGm1DJG/uxPKzFX8j694ti0ubiCCXfY8ihBAD026');
            INSERT INTO tableName (id,email,name,password) VALUES ('717', 'arianna.de.vries@trouwnutrition.com', 'Arianna', '$2y$10$4QvUnZ260vjR2fQt1vfrvuFRViwlPvM42TDqNR0XDp1XtkDhq1yJi');
            INSERT INTO tableName (id,email,name,password) VALUES ('739', 'guillermo.alva@skretting.com', 'Guillermo', '$2y$10$XIZ6q1waITyro1jScSG.Y.rK5ZYEphxJcZVxAu8OpGYkycxlpfnFS');
            INSERT INTO tableName (id,email,name,password) VALUES ('740', 'victor.baquerizo@trouwnutrition.com', 'Víctor', '$2y$10$ovLi2.sMIVixFc85Iy8ajOvz.S2JDoGkhQR7cU041DY8sEXU6lRF6');
            INSERT INTO tableName (id,email,name,password) VALUES ('741', 'walasortiz@gmail.com', 'Walfred', '$2y$10$/L2TF4iO1d5ZKWSGsXzbX.ybf60hG0dnmzr03MuQe0tvQRdjbJLeW');
            INSERT INTO tableName (id,email,name,password) VALUES ('742', 'csuarez@disatyr.com.pa', 'CARMEN ELINA', '$2y$10$hv872U7jCDXYDWaqfwxO0eXscpgHxN.BfrorDqYUDgP32bUAqaolK');
            INSERT INTO tableName (id,email,name,password) VALUES ('743', 'darguello@disatyr.com.pa', 'DAVID', '$2y$10$0UDUrK53yTGKNzirrZt6SOOA5oHdukvUb..74.MxS3COK2LFTv1j6');
            INSERT INTO tableName (id,email,name,password) VALUES ('744', 'emartinez@disatyrhn.com', 'EDWIN', '$2y$10$xoPkjskE9WaHNMzZtBUZqOfCuF4KoSE0bQ2I19tYOFjEQDMrn4pGu');
            INSERT INTO tableName (id,email,name,password) VALUES ('754', 'techcon@dominant-cz.cz', 'Roy', '$2y$10$Oq7geazZSwGiFnnW.iOQJOzTkskCbkcdnKAQtPz5kjq6M0y6vkKQa');
            INSERT INTO tableName (id,email,name,password) VALUES ('796', 'luis.duarte@petersime.com', 'Luis', '$2y$10$8yPIO4d4ojs8AMRWVRgnJOkmNIIBTgiSedv.lrx.HFK/hMqn32mFa');
            INSERT INTO tableName (id,email,name,password) VALUES ('818', 'njosa@igusol.com', 'Ignacio', '$2y$10$yVRPM75DJVMxCdm6DQXH3.l9SkdtLBKd17Jt8J31T7Vm8zgdESfje');
            INSERT INTO tableName (id,email,name,password) VALUES ('819', 'jmruiz@igusol.com', 'Juan Miguel', '$2y$10$tUPvp4RemdeSTTsosmBhIuXHZ9q6WUn64Dg8q2PjFfvaY/VQcO/uW');
            INSERT INTO tableName (id,email,name,password) VALUES ('820', 'jmgutierrez@produmix.com', 'José María', '$2y$10$iMNzYf7zNKv9sakvrs.61OXHMB.Y14a808HjYRSt6HugufX24nv/q');
            INSERT INTO tableName (id,email,name,password) VALUES ('821', 'amontero@igusol.com', 'Andrés', '$2y$10$C/idi1ma33CtbZ2tqU.Hl.5Os.Hqf0T0rAIUpnZ5a0mMAAAeL61nu');
            INSERT INTO tableName (id,email,name,password) VALUES ('826', 'magali.mora.changanaqui@merck.com', 'Magali', '$2y$10$4l2Xce4VJGhOd2wINhzgI.ioWAPXPdYi.LFRhI.8Ri40B/hHYSBaC');
            INSERT INTO tableName (id,email,name,password) VALUES ('829', 'suscripcionesgb@gmail.com', 'Gaston', '$2y$10$1zSSxHhayUspDLDUolP/1ulGAc57CUZR1.81QiSJVEQ6hNlJTnM/O');
            INSERT INTO tableName (id,email,name,password) VALUES ('830', 'lady.caceres@ita.international', 'Lady', '$2y$10$WBai7UR7pyC3vr3vTu5LlOk0PjQKiFDGc5hV4K69AEts3OmRInSWK');
            INSERT INTO tableName (id,email,name,password) VALUES ('831', 'ccamilocaceres@yahoo.com', 'Camilo', '$2y$10$rRdZ4viHnZlA8YBzqSxbheYgGui58pw0ud3gCv4lNjpnK6otDqKJ6');
            INSERT INTO tableName (id,email,name,password) VALUES ('834', 'carlos.jimenez@trouwnutrition.com', 'Carlos', '$2y$10$0MqjsRpI7H1DyJ3sKgdy6OEOMnJ0uCTFNBu/KCybnPw1XvUp8OGPS');
            INSERT INTO tableName (id,email,name,password) VALUES ('835', 'eduardo@grenpanama.com', 'Eduardo', '$2y$10$BQPUvYxzZuglivarBhlkHOfWzHjFmn9ylXszzfLTvAJJQxmm1UCsa');
            INSERT INTO tableName (id,email,name,password) VALUES ('860', 'gfgc04@gmail.com', 'GIANNI', '$2y$10$kwlyuPlTYyT5AXMkBzb/rOW.C5MplnldSPquFgUzzJk.koWsrpnRS');
            INSERT INTO tableName (id,email,name,password) VALUES ('867', 'samgenie@gmail.com', 'SAMUEL', '$2y$10$CS94x6yKMj7r2D6sJEwgYe93gAC276cBoogPeX.5TOrCWdH3Y7pXi');
            INSERT INTO tableName (id,email,name,password) VALUES ('1136', 'medina@bekaminversiones.com', 'Rebecca', '$2y$10$OTDzjm2a/jMOiSDEfB8GJOqzN/q8MFBFwDRb.8L.cu0ispmWAIuP.');
            INSERT INTO tableName (id,email,name,password) VALUES ('1303', 'j.alvarenga@realva.net', 'Jorge', '$2y$10$KrSoAAx971qMPZe7ttQL3.NazQkeYgkCYTCPvYVwsqnutrDJ.Er5m');
            INSERT INTO tableName (id,email,name,password) VALUES ('1304', 'r.whittington@schippers.eu', 'Robert', '$2y$10$D2z4n9JYnG/sBItDoe42j.8I6L6Wz7TdA0PHil.RPFPTSmx3w1qqC');
            INSERT INTO tableName (id,email,name,password) VALUES ('1305', 'julio.campos@sanfer.com.mx', 'Julio', '$2y$10$99KW0UOPCaLUup50509aHedFeWlBIXZQevcqeZj96F0U3Jvm3z2ke');
            INSERT INTO tableName (id,email,name,password) VALUES ('1435', 'jbenito.disatyr@gmail.com', 'JOSE BENITO', '$2y$10$ilCVu0fgRTIYeTNPXdMYTOb5uCaj.45VcRsarLDIoGtRbmBPn.6gq');
            INSERT INTO tableName (id,email,name,password) VALUES ('1436', 'ventas@disatyr.com.sv', 'MAURICIO', '$2y$10$Qq2NJdL5KCDUc069bffZqOTVNGHz3o.IWmZTe380pAgKt6BeI4CTy');
            INSERT INTO tableName (id,email,name,password) VALUES ('1437', 'tecnico.ventas16@disatyr.com.sv', 'FELIPE', '$2y$10$MR3MXEkqyLx/pQw0c8a5HeCC2JieWRKXNMxMftrfigQbqXhiWakh.');
            INSERT INTO tableName (id,email,name,password) VALUES ('1538', 'cphilippemanchec@raiz-up.com', 'Clémence', '$2y$10$FXOU90AcKtu2ac8Fc6qjV.tCo8DYf9gohnlmXwBZcn0HXfut4Phze');
            INSERT INTO tableName (id,email,name,password) VALUES ('1579', 'ovidio@dexibericadominicana.com', 'Rafael Olvido', '$2y$10$NTJ9y3E1J7ZOI1OcIy0/UexMhPsNG8kSyLBeuxOkQtrPt.2BCVDIO');
            INSERT INTO tableName (id,email,name,password) VALUES ('1580', 'h.anzola@dexiberica.com', 'Hector Manuel', '$2y$10$BMNKso0Oev7YtY/M9b214eHqajbb/XMj95avpoo2GkKazqVsWFeV6');
            INSERT INTO tableName (id,email,name,password) VALUES ('1594', 'm.bosch@dexiberica.com', 'Persi Paco', '$2y$10$qy048lh1LgBoMuI9mesDSu4M6/RDZPX5DhXK1S1m5kKUfApfbm8oi');
            INSERT INTO tableName (id,email,name,password) VALUES ('1595', 'pedrol@dexiberica.com', 'Gladys', '$2y$10$SOrs1Rpu1e6zsCAjGmvAt.cho5xqEB6MCDf1trToPDNTNtaqxI3o6');
            INSERT INTO tableName (id,email,name,password) VALUES ('1596', 'Darlyng.Ruiz@emtech-systems.com', 'Darlyng', '$2y$10$N9bE3hn7k/n70oh6VJaebugETUSshhc08oSP2LDbrSN96PGigfR6e');
            INSERT INTO tableName (id,email,name,password) VALUES ('1664', 'charlie.klein.gunnewiek@salmet.de', 'Charlie', '$2y$10$KRnzJarm/XCMeUdtGbBISet1A9Xw4QsxZpMm1mDXc.MBr5T2zX3CC');
            INSERT INTO tableName (id,email,name,password) VALUES ('1671', 'dcook@swsalesco.com', 'David', '$2y$10$8EgphB2XZ40EYFET2NyNU.8CP8WqpOKVuiava2OaNi3BJERVQmOoC');
            INSERT INTO tableName (id,email,name,password) VALUES ('1711', 'rcosorio@alkemycorp.com', 'Raquel Cristina', '$2y$10$Y1hJHvsDAz2vXQSo5Z9NSOpe1CPwCYB4C6OB6AkgAvfi4vnp.bL3a');
            INSERT INTO tableName (id,email,name,password) VALUES ('1712', 'lyamaya@alkemycorp.com', 'Laritza', '$2y$10$/JUVtekeMLhEZ7j4aV7/KORwlUj2/5pImPq37zsmIeAEMZiJ8Ms8W');
            INSERT INTO tableName (id,email,name,password) VALUES ('1725', 'b.betanco@realva.net', 'Belkis', '$2y$10$yAMbHXsEVEi086.0eWZrGODCyoG43HZWxWShn1KsD.CzDI3ml/1PK');
            INSERT INTO tableName (id,email,name,password) VALUES ('1731', 'k.velasquez@realva.net', 'KAREN', '$2y$10$kzYWWlkIVvpgrRwNAEvqJ.ra3d9rxRcSIv31I9zDuL/.FimHIC7aW');
            INSERT INTO tableName (id,email,name,password) VALUES ('1765', 'diana.aixa.torres.munoz@merck.com', 'Diana', '$2y$10$y8sLltpaI6i8WRyvhFBtg.NRkD3fP3Hmnx19rziG4spZQj2jVRjW.');
            INSERT INTO tableName (id,email,name,password) VALUES ('1766', 'ch@systel-international.com', 'CEDRIC', '$2y$10$qEfT/HI4J/8Ec8CA0Oq8auvGkRvZH9PM2U0B2C3abTAr.xgwxBLYO');
            INSERT INTO tableName (id,email,name,password) VALUES ('1770', 'lachacon@gartech.com.in', 'LUIS', '$2y$10$aMN4wfPwEO9PzKTBv6QotuZPhc839cqA7f/O58hdVXd1XwYES1QWq');
            INSERT INTO tableName (id,email,name,password) VALUES ('1771', 'papatil@gartech.com.in', 'PRASANNA', '$2y$10$5r/U3EtKYbWz90TzLS97ieAJ7nuzGkrErKFcRW4aI9CIoKYxuXqBi');
            INSERT INTO tableName (id,email,name,password) VALUES ('1772', 'garware@gartech.com.in', 'REKHA HARISH', '$2y$10$Qdf0j6zsQFVG.VLdP4u7bOZglfStqrQcaj2kBv3dR7VIJ6pH3IlTG');
            INSERT INTO tableName (id,email,name,password) VALUES ('1773', 'hrgarware@gartech.com.in', 'HARISH RAJARAM', '$2y$10$v1rjb0.1pNTJTYV3hOgfaeEIjpaP/6UwTHoT87rAV82Q4RtzMreUm');
            INSERT INTO tableName (id,email,name,password) VALUES ('1896', 'marina.rivera@campestre.com.sv', 'Marina', '$2y$10$mUHIJQ5cNb4UgJ9GDTuElO07K63OPQ7xjLAB0hxMgTmFICOiIdieG');
            INSERT INTO tableName (id,email,name,password) VALUES ('1908', 'vrvets2002@gmail.com', 'Dr. Raina', '$2y$10$Md29G2JUWUPon7fTK/tSKupcpFkv9cP5kSyzpb1Sd1e5aFqyGfBCC');
            INSERT INTO tableName (id,email,name,password) VALUES ('1911', 'acastillo@molinosantaana.com', 'Giovanni', '$2y$10$Rl0jwb05cz7q/YdhPcdMJ.NCuWQ61cetz9KXdinAm9B0wRlrrZOSC');
            INSERT INTO tableName (id,email,name,password) VALUES ('1922', 'jorge.piedrahita@trouwnutrition.com', 'Augustín', '$2y$10$1ZxScai23RXvRRhHnEzfxeodzONgTSmbIAxzeWQ4apl4tZQroE.kK');
            INSERT INTO tableName (id,email,name,password) VALUES ('1942', 'pjfuentes93@gmail.com', 'Jeremy', '$2y$10$HERYQHDytLp5hRs9gA/nluk9VtRRQPVKh2CAJV83bSboyC9J.QsiO');
            INSERT INTO tableName (id,email,name,password) VALUES ('1945', 'matteo.crema@libero.it', 'Matteo', '$2y$10$LR/jK0l9WeRvw9eRfyH78uPYUfh9KmcMLS4Md9QTgr6CpFt1Okrm.');
            INSERT INTO tableName (id,email,name,password) VALUES ('1946', 'gestionintegral@promitec.com.co', 'ALVARO JOSE', '$2y$10$oAiTINmKb2h8CAmfY6WU6O/uf2aCACFlUdUNRKW3cgKmPACNLeJNa');
            INSERT INTO tableName (id,email,name,password) VALUES ('1954', 'jovelmiranda@gmail.com', 'Rafael', '$2y$10$IHPSfBs58GdnsplVsqCgaer/ZBgbu6flG/JlHqTDgvdfS5JA75m7q');
            INSERT INTO tableName (id,email,name,password) VALUES ('1971', 'comunicaciones@promitec.com.co', 'ALVARO JOSE', '$2y$10$haOzQr4hwHPqDo7XsIDD3OnPbEj1ZjZ3U12ZXMsRJoLtkJ2R4t5Om');
            INSERT INTO tableName (id,email,name,password) VALUES ('1974', 'marketing@klimapad.com', 'Blanca Yaneth', '$2y$10$.l1fsyf8BqIRe4kfIJycHOT4ulo6HyiBFkmh2Ddx9wFkJneKkmJuu');
            INSERT INTO tableName (id,email,name,password) VALUES ('1987', 'Jluisdiaz611@hotmail.com', 'Jose Luis', '$2y$10$rtZgKfYE8Hcv8Z0JHu2bquMIZl36j7FJGrFpyzSwSRvXVgkMAmQB2');
            INSERT INTO tableName (id,email,name,password) VALUES ('2025', 'allison.kawaoku@hendrix-genetics.com', 'Allison', '$2y$10$E9EqxC1g4jh1EHv6RjeUFOxHYrAkSVWXamb32Jsd.M0tfy7mWexWK');
            INSERT INTO tableName (id,email,name,password) VALUES ('2026', 'csalazar@alltech.com', 'CRISTIAN', '$2y$10$oo2dSDk4eYM7v0t41.TG/O5PIn9yQEn9leVlwjSMwefVW5IcuYPbe');
            INSERT INTO tableName (id,email,name,password) VALUES ('2027', 'vferrerasmatos@gmail.com', 'VIANNELy', '$2y$10$68Du744x1VmI8B8o7dtYcOA0.FR8YeQher969N1wyiCzzIAShUvkq');
            INSERT INTO tableName (id,email,name,password) VALUES ('2028', 'viannelyferreras@hotmail.com', 'VIANNELy', '$2y$10$8LHXWUH0J4ZRwJuFUz9ED.04SZLfWfJhonBIwNOTzrPkCOE0w62DO');
            INSERT INTO tableName (id,email,name,password) VALUES ('2029', 'viannelyf@hotmail.com', 'VIANNELY', '$2y$10$Fy0Rix.uwxbGzCVUukiLDuAoKQKzrvnyCGaZdSzf2O.Wq5fyTH/jC');
            INSERT INTO tableName (id,email,name,password) VALUES ('2053', 'gmtumbes@gmail.com', 'WILLIAM', '$2y$10$xox9jWu.7g0SA86weJzZjuSKmCl7YgPydKoV3l2WQK3KqTRQd.HhO');
            INSERT INTO tableName (id,email,name,password) VALUES ('2076', 'rlopez@lambtonconveyor.com', 'ROBERTO JAVIER', '$2y$10$vZdWE7Dw/Qoi0Kqasjk9JOlty.ZJz26Bu6Uf4viP3908K6p7gd2tG');
            INSERT INTO tableName (id,email,name,password) VALUES ('2099', 'jacob.broekema@walinga.com', 'JACOb', '$2y$10$xYufZxvhQ7HPgtngsWouEOI6HKLkzOGQHjo3spblRWJoE19JIzOfS');
            INSERT INTO tableName (id,email,name,password) VALUES ('2100', 'pamb@walinga', 'PAUl', '$2y$10$8ptbtDebCl57ytRmTSXpneWC3RsoxQeeYOsU8EDrOE.xNzhbR861G');
            INSERT INTO tableName (id,email,name,password) VALUES ('2101', 'jose.carpenteri@walinga.com', 'JOSE AGUSTIn', '$2y$10$DzEfHDBAmF0rfyGCXiSqLO1Z83hFLmnDbEvfQ5Ou5i1/GjvKOqi86');
            INSERT INTO tableName (id,email,name,password) VALUES ('2148', 'Rafaelsandoval007@hotmail.com', 'Rafael', '$2y$10$YN5HGQ02GHS782iPgRKXAeK/UAkSZG01QyIeAJL2vuKN.YlZthLj2');
            INSERT INTO tableName (id,email,name,password) VALUES ('2175', 'pamb@walinga.com', 'PAUl', '$2y$10$O44WnaBmul1NZMaNKaGt7.sV9ELaE5io.sPquJ3ty56vaibi0qhdS');
            INSERT INTO tableName (id,email,name,password) VALUES ('2176', 'ltoledo8270@gmail.com', 'LAUREN', '$2y$10$VxXOcKPcthONKcJu9GZj3.65kbXp/BomWsNznWQtXecHunB2RWX/2');
            INSERT INTO tableName (id,email,name,password) VALUES ('2182', 'rcorzo48@hotmail.com', 'Jose Ruben', '$2y$10$P//bPpRNt31S0N.Go7unYOjLIlT9Y54gwfJjLtXJG4JtJ9IVDJsr6');
            INSERT INTO tableName (id,email,name,password) VALUES ('2190', 'rfernandez@scancotec.com', 'Ronny', '$2y$10$NXuj662cV9rLUh232Ii47.YZyxLxVZZJ9jlGXcqy8Fqsq7gByRoT2');
            INSERT INTO tableName (id,email,name,password) VALUES ('2199', 'walter.martinez.matamoros@gmail.com', 'WALTER ALEJANDRo', '$2y$10$l3N83GZd8.ROKdfs95rB9u0W3SRBKG7JABIdqDPqFWy5R8RQDWxUu');
            INSERT INTO tableName (id,email,name,password) VALUES ('2202', 'DOMINGO.RODRIGUEZ@HIPRA.COM', 'DOMINGO JOSE', '$2y$10$PtIg3g7Uu8p6WGhhZgfjNuaGAOhxaY.Kq4wGDHBLCFL3WNxdDmnFW');
            INSERT INTO tableName (id,email,name,password) VALUES ('2203', 'DR.RODRIGUEZ2016@OUTLOOK.COM', 'DOMINGO JOSE', '$2y$10$w4WTZzxwh5DlPx.Xijbf2uYV79LrwsUDVkO..7dHFI4ieel0IQ6/2');
            INSERT INTO tableName (id,email,name,password) VALUES ('2219', 'oriolgispert@hotmail.com', 'JOSE ORIOl', '$2y$10$qDaDsJPh5ldK7fqpzc6KieK8wM8YH6tGgXYKj6aPREobKoqdc/B8W');
            INSERT INTO tableName (id,email,name,password) VALUES ('2221', 'vpvidiella@gmail.com', 'VICTOR ALEXANDRe', '$2y$10$E/j/Bv7BXl3nlPG72/WjtuxvSyN89rW.CPZ1/7lJhnEyeLTZJHSz2');
            INSERT INTO tableName (id,email,name,password) VALUES ('2225', 'lydiavidiella@hotmail.com', 'LIDIa', '$2y$10$mVgNZlrVsgR5RoN3jY5bgudIpL7aDh2Pav8UMO3YrNDsB0LlPQme6');
            INSERT INTO tableName (id,email,name,password) VALUES ('2229', 'anna.vidielladuch@gmail.com', 'PAULa', '$2y$10$1Xh7anO385r6rWbuazXXd.o/HFxpzLBFp.s0umFb5L4RZspKq0D0y');
            INSERT INTO tableName (id,email,name,password) VALUES ('2241', 'Jorge orge.Jimenez@vitalialimentos.com', 'JORGE FRANCISCo', '$2y$10$gGbP3iWFAqZk4TfSl3GohujVBdzy64lY7EeGxVnEBDBWfU5grNKU6');
            INSERT INTO tableName (id,email,name,password) VALUES ('2242', 'elysa.miranda@vitalialimentos.com', 'JORGE FRANCISCo', '$2y$10$vbwhyQxNMRzZ3it8HiDDR.pB2v0bYslbM9Sg4W1MN6NfhwKU9lBXe');
            INSERT INTO tableName (id,email,name,password) VALUES ('2244', 'claudia.reyes@vitalialimentos.com', 'CLAUDIA ELENA', '$2y$10$LVWDJGar9UzyvrzbXaK2MeCkWfjTk8XlHfJcuYbT3zCpJ8v9Qg4qG');
            INSERT INTO tableName (id,email,name,password) VALUES ('2245', 'claudia.reyes@criaves.com.sv', 'CLAUDIA ELENA', '$2y$10$RMOHlfDw3Aa/IhORuzYuWeZpFO/tV9GKut7dDv81lq73z1nm8FM0a');
            INSERT INTO tableName (id,email,name,password) VALUES ('2247', 'analauradelavega@hotmail.com', 'Ana Laura', '$2y$10$NfWunMVHJMCF2WGzjFA/ieZboDVDZtGX0dhflj1KyonaiZpHknyL6');
            INSERT INTO tableName (id,email,name,password) VALUES ('2257', 'roberto.arias@criaves.com.sv', 'ROBERTO', '$2y$10$nmlK4SftkCAIOlFH/PWzXe.n8yxQwYw80N8e0/tcR0NECW8GMgTFi');
            INSERT INTO tableName (id,email,name,password) VALUES ('2258', 'roberto.arias@vitalialimentos.com', 'ROBERTo', '$2y$10$UbWqMf9D/kmz3nFhYgEq8ud4hpyf2g7AsVQCtROUullXJqg.LE5mm');
            INSERT INTO tableName (id,email,name,password) VALUES ('2260', 'manuel.moran@vitalialimentos.com', 'MANUEL DE JESUS', '$2y$10$uH.GLfohz9W5WIIt4cy9QOwPNUlhmsRbBC5ZPfKYJhtl98WK5G41S');
            INSERT INTO tableName (id,email,name,password) VALUES ('2262', 'manuel.moran@criaves.com.sv', 'MANUEL DE JESUS', '$2y$10$/0YgpO44SOFxyt8oBDM7EeV9m48MDgU76KkcqtEkBmnlxQczGPp8a');
            INSERT INTO tableName (id,email,name,password) VALUES ('2263', 'hector.valero@vitalialimentos.com', 'HECTOR', '$2y$10$LhFQgsN5x61RwcuVJyqEW.sDMuqswYGvLBdD8dqK8GSIHb/1De2Ou');
            INSERT INTO tableName (id,email,name,password) VALUES ('2285', 'erazopj@gmail.com', 'JOSE  MANUEl', '$2y$10$4tmjs4jEm7FHLOyzXLWUwOMo8IA9oyEZPlzE1vybE2yK5SrYxPI2.');
            `
        )
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
